# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-11-03 18:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploaders', '0003_auto_20180603_1000'),
        ('noksfishes', '0014_auto_20180611_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rat', models.FloatField(default=0.0)),
                ('shr', models.FloatField(default=0.0)),
                ('publication', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_publication_short', to='noksfishes.Publication')),
                ('upload_info', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tv_short', to='uploaders.UploadedInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TvChannelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField()),
                ('channel', models.CharField(max_length=255, verbose_name='Канал')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('media_group', models.CharField(max_length=255, verbose_name='Медиа группа')),
                ('time_rate', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Рейтинг по времени')),
                ('publication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tv_publication', to='noksfishes.Publication')),
                ('upload_info', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tv', to='uploaders.UploadedInfo')),
            ],
        ),
    ]
