# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.IntegerField()),
                ('platform', models.IntegerField()),
                ('browser', models.IntegerField()),
                ('region', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('income', models.IntegerField()),
                ('uniques', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Analyzed Info',
                'verbose_name_plural': 'Analyzed Info',
            },
        ),
    ]
