# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploaders', '0001_initial'),
        ('admixer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedinfo',
            name='upload_info',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admixer', to='uploaders.UploadedInfo'),
        ),
    ]
