# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-16 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admixer', '0002_analyzedinfo_upload_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedinfo',
            name='region',
            field=models.CharField(blank=True, default='UA', max_length=256, null=True),
        ),
    ]
