# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043c\u0430/\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f')),
                ('code', models.PositiveIntegerField(verbose_name='\u041a\u043e\u0434')),
                ('url', models.URLField(max_length=255, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('site', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('posted_date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': 'Analyzed Info',
                'verbose_name_plural': 'Analyzed Info',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=255, verbose_name='\u041a\u043b\u044e\u0447\u0435\u0432\u043e\u0435 \u0441\u043b\u043e\u0432\u043e')),
                ('title', models.CharField(max_length=512, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('inserted_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0432 \u0431\u0430\u0437\u0443')),
                ('posted_date', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0432\u044b\u0445\u043e\u0434\u0430')),
                ('posted_time', models.TimeField(verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u0445\u043e\u0434\u0430')),
                ('category', models.CharField(max_length=255, verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('priority', models.CharField(max_length=255, verbose_name='\u0412\u0430\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('advertisement', models.CharField(max_length=255, verbose_name='\u0420\u0435\u043a\u043b\u0430\u043c\u0430')),
                ('size', models.PositiveIntegerField(verbose_name='\u0420\u0430\u0437\u043c\u0435\u0440')),
                ('symbols', models.PositiveIntegerField(verbose_name='\u0417\u043d\u0430\u043a\u043e\u0432')),
                ('publication', models.CharField(max_length=255, verbose_name='\u0418\u0437\u0434\u0430\u043d\u0438\u0435')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041f\u0435\u0440\u0432\u043e\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
                ('country', models.CharField(max_length=255, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430')),
                ('region', models.CharField(max_length=255, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
                ('city', models.CharField(max_length=255, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('regionality', models.CharField(max_length=255, verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0422\u0438\u043f \u0418\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('topic', models.CharField(max_length=255, verbose_name='\u0412\u0438\u0434 \u0418\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('consolidated_type', models.CharField(max_length=255, verbose_name='\u0421\u0432\u043e\u0434\u043d\u044b\u0439 \u0442\u0438\u043f')),
                ('number', models.PositiveIntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0438\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('printing', models.PositiveIntegerField(verbose_name='\u0422\u0438\u0440\u0430\u0436')),
                ('page', models.CharField(max_length=255, verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
                ('fill_rate', models.PositiveIntegerField(verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433 \u043d\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u044f')),
                ('user', models.CharField(max_length=255, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
                ('author_tone', models.CharField(max_length=255, verbose_name='\u0422\u043e\u043d \u0430\u0432\u0442\u043e\u0440\u0430')),
                ('event_tone', models.CharField(max_length=255, verbose_name='\u0422\u043e\u043d \u0441\u043e\u0431\u044b\u0442\u0438\u044f')),
                ('general_tone', models.CharField(max_length=255, verbose_name='\u0422\u043e\u043d \u041e\u0431\u0449\u0438\u0439')),
                ('objectivity', models.CharField(max_length=255, verbose_name='\u041e\u0431\u044a\u0435\u043a\u0442\u043d\u043e\u0441\u0442\u044c')),
                ('mention_type', models.CharField(max_length=255, verbose_name='\u0412\u0438\u0434 \u0443\u043f\u043e\u043c\u0438\u043d\u0430\u043d\u0438\u044f')),
                ('eventivity', models.CharField(max_length=255, verbose_name='\u0421\u043e\u0431\u044b\u0442\u0438\u0439\u043d\u043e\u0441\u0442\u044c')),
                ('subject', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u0422\u0435\u043c\u0430\u0442\u0438\u043a\u0438')),
                ('plot', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0421\u044e\u0436\u0435\u0442\u044b')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
                ('top_managers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Top-\u043c\u0435\u043d\u0434\u0436\u0435\u0440\u044b')),
                ('companies', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u0438')),
                ('heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0420\u0443\u0431\u0440\u0438\u043a\u0430')),
                ('annotation', models.TextField(blank=True, null=True, verbose_name='\u0410\u043d\u043d\u043e\u0442\u0430\u0446\u0438\u044f')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u043b\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='\u041f\u043e\u0434\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='\u0421\u043f\u0440\u0430\u0432\u043a\u0430')),
                ('w', models.FloatField(verbose_name='W')),
                ('y', models.FloatField(verbose_name='Y')),
                ('z', models.FloatField(verbose_name='Z')),
                ('fc', models.FloatField(verbose_name='\u0424\u0421')),
                ('r', models.FloatField(verbose_name='R')),
                ('ce', models.FloatField(verbose_name='\u0421\u042d')),
                ('f', models.FloatField(verbose_name='F')),
                ('r_small', models.FloatField(verbose_name='r')),
                ('s', models.FloatField(verbose_name='S')),
                ('e', models.FloatField(verbose_name='E')),
                ('ta', models.FloatField(verbose_name='Ta')),
                ('ts', models.FloatField(verbose_name='Ts')),
                ('tc', models.FloatField(verbose_name='Tc')),
                ('tmk', models.FloatField(verbose_name='Tmk')),
                ('tmc', models.FloatField(verbose_name='Tmc')),
                ('l', models.FloatField(verbose_name='L')),
                ('d', models.FloatField(verbose_name='D')),
                ('ktl', models.FloatField(verbose_name='Ktl')),
                ('kt', models.FloatField(verbose_name='kt')),
                ('kl', models.FloatField(verbose_name='kl')),
                ('m', models.FloatField(verbose_name='M')),
                ('pg', models.FloatField(verbose_name='Pg')),
                ('h', models.FloatField(verbose_name='H')),
                ('result', models.FloatField(verbose_name='\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442')),
                ('periodicity', models.CharField(max_length=255, verbose_name='\u041f\u0435\u0440\u0438\u043e\u0434\u0438\u0447\u043d\u043e\u0441\u0442\u044c')),
                ('activity', models.FloatField(verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u0438\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('marginality', models.FloatField(verbose_name='\u041c\u0430\u0440\u0433\u0438\u043d\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
                ('cost', models.FloatField(verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c')),
                ('visitors', models.FloatField(verbose_name='\u041f\u043e\u0441\u0435\u0442\u0438\u0442\u0435\u043b\u0435\u0439')),
                ('citation_index', models.FloatField(verbose_name='\u0418\u043d\u0434\u0435\u043a\u0441 \u0446\u0438\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f')),
                ('width', models.FloatField(verbose_name='\u0428\u0438\u0440\u0438\u043d\u0430')),
                ('k1', models.FloatField(verbose_name='k1')),
                ('k2', models.FloatField(verbose_name='k2')),
                ('k3', models.FloatField(verbose_name='k3')),
                ('dtek_kof', models.FloatField(verbose_name='\u0414\u0422\u042d\u041a \u043a\u043e\u044d\u0444\u0444\u0438\u0446\u0438\u0435\u043d\u0442')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('edit_date', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041f\u043e\u043c\u0435\u0442\u043a\u0430')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043c\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='ShukachPublication',
            fields=[
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='noksfishes.Publication')),
                ('shukach_id', models.IntegerField()),
            ],
        ),
    ]
