# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0002_auto_20171129_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='edition_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u0438\u0437\u0434\u0430\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='publication',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432\u044b\u0445\u043e\u0434\u0430'),
        ),
    ]
