# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-03 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0003_auto_20180406_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Рынок')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='object',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='publication',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_publications', to='noksfishes.Market', verbose_name='ID Рынка'),
        ),
    ]
