# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0004_auto_20180603_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='activity',
            field=models.FloatField(blank=True, null=True, verbose_name='Активность издания'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='advertisement',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Реклама'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='author_tone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тон автора'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ce',
            field=models.FloatField(blank=True, null=True, verbose_name='СЭ'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='citation_index',
            field=models.FloatField(blank=True, null=True, verbose_name='Индекс цитирования'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='consolidated_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сводный тип'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='d',
            field=models.FloatField(blank=True, null=True, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='dtek_kof',
            field=models.FloatField(blank=True, null=True, verbose_name='ДТЭК коэффициент'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='e',
            field=models.FloatField(blank=True, null=True, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='event_tone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тон события'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='eventivity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Событийность'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='f',
            field=models.FloatField(blank=True, null=True, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='fc',
            field=models.FloatField(blank=True, null=True, verbose_name='ФС'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='fill_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рейтинг наполнения'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='general_tone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тон Общий'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='h',
            field=models.FloatField(blank=True, null=True, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='k1',
            field=models.FloatField(blank=True, null=True, verbose_name='k1'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='k2',
            field=models.FloatField(blank=True, null=True, verbose_name='k2'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='k3',
            field=models.FloatField(blank=True, null=True, verbose_name='k3'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='kl',
            field=models.FloatField(blank=True, null=True, verbose_name='kl'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='kt',
            field=models.FloatField(blank=True, null=True, verbose_name='kt'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ktl',
            field=models.FloatField(blank=True, null=True, verbose_name='Ktl'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='l',
            field=models.FloatField(blank=True, null=True, verbose_name='L'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='m',
            field=models.FloatField(blank=True, null=True, verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='marginality',
            field=models.FloatField(blank=True, null=True, verbose_name='Маргинальность'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='mention_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид упоминания'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер издания'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='objectivity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Объектность'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='periodicity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pg',
            field=models.FloatField(blank=True, null=True, verbose_name='Pg'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='posted_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выхода'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='printing',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='priority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Издание'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='r',
            field=models.FloatField(blank=True, null=True, verbose_name='R'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='r_small',
            field=models.FloatField(blank=True, null=True, verbose_name='r'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='regionality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Региональность'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='result',
            field=models.FloatField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='s',
            field=models.FloatField(blank=True, null=True, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='symbols',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Знаков'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ta',
            field=models.FloatField(blank=True, null=True, verbose_name='Ta'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tc',
            field=models.FloatField(blank=True, null=True, verbose_name='Tc'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tmc',
            field=models.FloatField(blank=True, null=True, verbose_name='Tmc'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tmk',
            field=models.FloatField(blank=True, null=True, verbose_name='Tmk'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид Издания'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ts',
            field=models.FloatField(blank=True, null=True, verbose_name='Ts'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='visitors',
            field=models.FloatField(blank=True, null=True, verbose_name='Посетителей'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='w',
            field=models.FloatField(blank=True, null=True, verbose_name='W'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='z',
            field=models.FloatField(blank=True, null=True, verbose_name='Z'),
        ),
    ]
