# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0006_auto_20180603_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='key_material',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Тематики'),
        ),
    ]
