# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0007_publication_key_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='key_word',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключевое слово'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Заголовок'),
        ),
    ]
