# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-06 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0009_auto_20180606_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='source',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Первоисточник'),
        ),
    ]
