# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0012_auto_20180607_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='Первоисточник'),
        ),
    ]
