# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0013_auto_20180607_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.TextField(blank=True, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='key_material',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевой материал'),
        ),
    ]
