# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noksfishes', '0014_auto_20180611_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdeptPublication',
            fields=[
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='noksfishes.Publication')),
                ('adept_id', models.IntegerField()),
            ],
        ),
    ]
