# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedinfo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
