# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 09:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analyzed Info',
                'verbose_name_plural': 'Analyzed Info',
            },
        ),
        migrations.CreateModel(
            name='SocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
                ('sex', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('age', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('education', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('children_lt_16', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('marital_status', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('occupation', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('group', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('income', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('region', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('typeNP', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
