# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noksfishes', '0001_initial'),
        ('factrum_group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdetails',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noksfishes.Theme'),
        ),
    ]
