# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factrum_group', '0002_socialdetails_title'),
        ('noksfishes', '0001_initial'),
        ('uploaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialdetails',
            name='upload_info',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='factrum_group_detailed', to='uploaders.UploadedInfo'),
        ),
        migrations.AddField(
            model_name='analyzedinfo',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noksfishes.Publication'),
        ),
        migrations.AddField(
            model_name='analyzedinfo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noksfishes.Theme'),
        ),
        migrations.AddField(
            model_name='analyzedinfo',
            name='upload_info',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='factrum_group', to='uploaders.UploadedInfo'),
        ),
    ]
