# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 17:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factrum_group', '0003_auto_20171129_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationsSocialDemoRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication', models.CharField(max_length=1024)),
                ('views', models.IntegerField()),
                ('sex', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('age', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('education', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('children_lt_16', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('marital_status', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('occupation', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('group', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('income', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('region', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('typeNP', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
